### PR TITLE
fixes typos in comments / docs

### PR DESCRIPTION
**Pull request by ordago**
## Description

Fixes typos in comments / docs. Doesn't modify code.

## Motivation and context

Why is this change required? What problem does it solve?

Fixes typos.

## How has this been tested?

Please describe in detail how you tested your changes.

I checked none of the typo fixes were alternative spellings. Testing environment: DuckDuckGo.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [ ] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

### CODE REVIEW

**Comment by ordago** [comment]
I also saw Callacks instead of Callbacks, but I didn't want to made code changes in the same PR

https://github.com/Crell/Serde/blob/a60209def2d11631bcbbfc2275d6a86135bf55ed/src/Attributes/ClassSettings.php#L33

**Review by Crell — APPROVED** [review]
D'Oh!  You never find all the typos until someone else is reading it. :smile:  Thanks.

**Comment by Crell** [comment]
Can you file another PR for the callacks issue?  That's a public property, yes, but not part of the public API (it's used internally) so I'm comfortable fixing it.

**Comment by ordago** [comment]
> Can you file another PR for the callacks issue? That's a public property, yes, but not part of the public API (it's used internally) so I'm comfortable fixing it.

👍 I'll PR the change for the property later

**Pull request merged**
